#### Que : Python Program for n-th Fibonacci number

Fibonacci series --- a series of numbers in which each number (Fibonacci number) is the sum of the two preceding numbers. The simplest is the series 1, 1, 2, 3, 5, 8, etc.

In [1]:
N = int(input("Enter the number of terms : "))
 
# first two terms are f1, f2 equal to 0 and 1 respectively
f1, f2 = 0, 1
count = 0
 
# checking for invalid inputs
if(N <= 0):
    print("Invalid Input, Kindly enter number greater than 0")
 
# if only one number in the sequence
elif(N == 1):
    print("Generating Fibonacci Sequence upto ", N, ": ")
    print(f1)
 
# for all the other cases, i.e. when N > 1
else:
    print("Generating Fibonacci sequence upto ", N, ": ")
    while count < N:
        print(f1)
        fth = f1 + f2
# swapping the values for f1 and f2
        f1 = f2
        f2 = fth
        count += 1

Enter the number of terms : 10
Generating Fibonacci sequence upto  10 : 
0
1
1
2
3
5
8
13
21
34


#### Que : Python Program for How to check if a given number is Fibonacci number?

In [2]:
# python program to check if x is a perfect square
import math
 
# A utility function that returns true if x is perfect square
def isPerfectSquare(x):
    s = int(math.sqrt(x))
    return s*s == x
 
# Returns true if n is a Fibinacci Number, else false
def isFibonacci(n):
 
    # n is Fibinacci if one of 5*n*n + 4 or 5*n*n - 4 or both
    # is a perferct square
    return isPerfectSquare(5*n*n + 4) or isPerfectSquare(5*n*n - 4)
    
# A utility function to test above functions
for i in range(1,11):
     if (isFibonacci(i) == True):
         print (i,"is a Fibonacci Number")
     else:
         print (i,"is a not Fibonacci Number ")

1 is a Fibonacci Number
2 is a Fibonacci Number
3 is a Fibonacci Number
4 is a not Fibonacci Number 
5 is a Fibonacci Number
6 is a not Fibonacci Number 
7 is a not Fibonacci Number 
8 is a Fibonacci Number
9 is a not Fibonacci Number 
10 is a not Fibonacci Number 


#### QUE : Python Program for Sum of squares of first n natural numbers

In [3]:
def sqsum(n) :
   sm = 0
   for i in range(1, n+1) :
      sm = sm + i**2
   print("Sum of square of first",n, "natural numbers is",sum)

sqsum(5)

Sum of square of first 5 natural numbers is <built-in function sum>


#### Que : Python Program for cube sum of first n natural numbers

In [4]:
def sqsum(n) :
   sm = 0
   for i in range(1, n+1) :
      sm = sm + (i*i*i)
   print("Sum of cubes of first",n, "natural numbers is",sm)

sqsum(5)

Sum of cubes of first 5 natural numbers is 225


#### Que : Python Program to find sum of array

In [5]:
import numpy as np

array = np.array([10,20,30,40,50])
print(type(array))
array.sum()

<class 'numpy.ndarray'>


150

#### Que : Python Program to find largest element in an array

In [6]:
array.max()

50

#### Que : Python Program for array rotation

In [7]:
import numpy as np

a = np.arange(0,10)
b = np.arange(-11,-1)

ar = np.array([a,b])

print (ar)
print (ar.shape)

ar = np.rot90(ar, 3)
print (np.fliplr(ar))
print (ar.shape)

[[  0   1   2   3   4   5   6   7   8   9]
 [-11 -10  -9  -8  -7  -6  -5  -4  -3  -2]]
(2, 10)
[[  0 -11]
 [  1 -10]
 [  2  -9]
 [  3  -8]
 [  4  -7]
 [  5  -6]
 [  6  -5]
 [  7  -4]
 [  8  -3]
 [  9  -2]]
(10, 2)


#### Que : Python Program to Split the array and add the first part to the end

In [8]:
def splitArr(arr, n, k): 
    for i in range(0, k): 
        x = arr[0]
        for j in range(0, n-1):
            arr[j] = arr[j + 1]
          
        arr[n-1] = x
          

In [9]:
arr = [10,20,30,40,50,60,70]
n = len(arr)
position = 2
  
splitArr(arr, n, position)
  
for i in range(0, n): 
    print(arr[i], end = ' ')

30 40 50 60 70 10 20 